# -*- coding: utf-8 -*-
"""TEST4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yhA8MHgaluG7VtVA__M6kDqKjsQCTJ1_
"""

import os
import re

directory = "/etc/NetworkManager/system-connections/"
files = os.listdir(directory)

for file in files:
    with open(os.path.join(directory, file), "r") as f:
        contents = f.read()
        connection_name = re.search('ssid=(\w+)', contents)
        password = re.search('psk=(\w+)', contents)

        if connection_name and password:
            print(f"Device Name: {connection_name.group(1)}")
            print(f"Password: {password.group(1)}")
            print("-" * 20)